# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4ce9d998bc0fcf569b5260d3a0f48a158a1cbf43440bd6ba2d582c9e8ba130230876c2021e3487935d291f8c0cf6b98e21b01530e6cbdbcc1d9b0ad6c7b9c31

test:
  secret_key_base: 4705b7c595d1e1cd31cdc6aeffab0773ac54c8ab2cc1f034cd03f404e2d5612eac305251b1e40d774bc5c59b35bffa290964d4e3a45c3114101ec95c344edf9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
